package thaumcraft.common.config;
import java.util.HashSet;
import java.util.Iterator;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.init.PotionTypes;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTBase;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.potion.PotionType;
import net.minecraft.potion.PotionUtils;
import net.minecraftforge.common.ForgeModContainer;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.fluids.FluidUtil;
import net.minecraftforge.fml.common.eventhandler.Event;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectEventProxy;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.api.aspects.AspectRegistryEvent;
import thaumcraft.api.blocks.BlocksTC;
import thaumcraft.api.internal.CommonInternals;
import thaumcraft.api.items.ItemsTC;
import thaumcraft.common.lib.crafting.ThaumcraftCraftingManager;


public class ConfigAspects
{
    public static String[] dyes;
    
    public static void postInit() {
        CommonInternals.objectTags.clear();
        registerItemAspects();
        registerEntityAspects();
        AspectRegistryEvent are = new AspectRegistryEvent();
        are.register = new AspectEventProxy();
        MinecraftForge.EVENT_BUS.post(are);
    }
    
    private static void registerEntityAspects() {
        ThaumcraftApi.registerEntityTag("Zombie", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 10).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerEntityTag("Husk", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 10).add(Aspect.FIRE, 5));
        ThaumcraftApi.registerEntityTag("Giant", new AspectList().add(Aspect.UNDEAD, 25).add(Aspect.MAN, 15).add(Aspect.EARTH, 10));
        ThaumcraftApi.registerEntityTag("Skeleton", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerEntityTag("WitherSkeleton", new AspectList().add(Aspect.UNDEAD, 25).add(Aspect.MAN, 5).add(Aspect.ENTROPY, 10));
        ThaumcraftApi.registerEntityTag("Creeper", new AspectList().add(Aspect.PLANT, 15).add(Aspect.FIRE, 15));
        ThaumcraftApi.registerEntityTag("Creeper", new AspectList().add(Aspect.PLANT, 15).add(Aspect.FIRE, 15).add(Aspect.ENERGY, 15), new ThaumcraftApi.EntityTagsNBT("powered", 1));
        ThaumcraftApi.registerEntityTag("Horse", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Donkey", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Mule", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("SkeletonHorse", new AspectList().add(Aspect.BEAST, 5).add(Aspect.UNDEAD, 10).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("ZombieHorse", new AspectList().add(Aspect.BEAST, 10).add(Aspect.UNDEAD, 5).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Pig", new AspectList().add(Aspect.BEAST, 10).add(Aspect.EARTH, 10).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerEntityTag("XPOrb", new AspectList().add(Aspect.MIND, 10));
        ThaumcraftApi.registerEntityTag("Sheep", new AspectList().add(Aspect.BEAST, 10).add(Aspect.EARTH, 10));
        ThaumcraftApi.registerEntityTag("Cow", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 15));
        ThaumcraftApi.registerEntityTag("MushroomCow", new AspectList().add(Aspect.BEAST, 15).add(Aspect.PLANT, 15).add(Aspect.EARTH, 15));
        ThaumcraftApi.registerEntityTag("SnowMan", new AspectList().add(Aspect.COLD, 10).add(Aspect.MAN, 5).add(Aspect.MECHANISM, 5).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerEntityTag("Ozelot", new AspectList().add(Aspect.BEAST, 10).add(Aspect.ENTROPY, 10));
        ThaumcraftApi.registerEntityTag("Chicken", new AspectList().add(Aspect.BEAST, 5).add(Aspect.FLIGHT, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Squid", new AspectList().add(Aspect.BEAST, 5).add(Aspect.WATER, 10));
        ThaumcraftApi.registerEntityTag("Wolf", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 10).add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerEntityTag("Bat", new AspectList().add(Aspect.BEAST, 5).add(Aspect.FLIGHT, 5).add(Aspect.DARKNESS, 5));
        ThaumcraftApi.registerEntityTag("Spider", new AspectList().add(Aspect.BEAST, 10).add(Aspect.ENTROPY, 10).add(Aspect.TRAP, 10));
        ThaumcraftApi.registerEntityTag("Slime", new AspectList().add(Aspect.LIFE, 10).add(Aspect.WATER, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerEntityTag("Ghast", new AspectList().add(Aspect.UNDEAD, 15).add(Aspect.FIRE, 15));
        ThaumcraftApi.registerEntityTag("PigZombie", new AspectList().add(Aspect.UNDEAD, 15).add(Aspect.FIRE, 15).add(Aspect.BEAST, 10));
        ThaumcraftApi.registerEntityTag("Enderman", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.MOTION, 15).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerEntityTag("CaveSpider", new AspectList().add(Aspect.BEAST, 5).add(Aspect.DEATH, 10).add(Aspect.TRAP, 10));
        ThaumcraftApi.registerEntityTag("Silverfish", new AspectList().add(Aspect.BEAST, 5).add(Aspect.EARTH, 10));
        ThaumcraftApi.registerEntityTag("Blaze", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.FIRE, 15).add(Aspect.FLIGHT, 5));
        ThaumcraftApi.registerEntityTag("LavaSlime", new AspectList().add(Aspect.WATER, 5).add(Aspect.FIRE, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerEntityTag("EnderDragon", new AspectList().add(Aspect.ELDRITCH, 50).add(Aspect.BEAST, 30).add(Aspect.ENTROPY, 50).add(Aspect.FLIGHT, 10));
        ThaumcraftApi.registerEntityTag("WitherBoss", new AspectList().add(Aspect.UNDEAD, 50).add(Aspect.ENTROPY, 25).add(Aspect.FIRE, 25));
        ThaumcraftApi.registerEntityTag("Witch", new AspectList().add(Aspect.MAN, 15).add(Aspect.MAGIC, 5).add(Aspect.ALCHEMY, 10));
        ThaumcraftApi.registerEntityTag("Villager", new AspectList().add(Aspect.MAN, 15));
        ThaumcraftApi.registerEntityTag("VillagerGolem", new AspectList().add(Aspect.METAL, 15).add(Aspect.MAN, 5).add(Aspect.MECHANISM, 5).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerEntityTag("EnderCrystal", new AspectList().add(Aspect.ELDRITCH, 15).add(Aspect.AURA, 15).add(Aspect.LIFE, 15));
        ThaumcraftApi.registerEntityTag("ItemFrame", new AspectList().add(Aspect.SENSES, 5).add(Aspect.CRAFT, 5));
        ThaumcraftApi.registerEntityTag("Painting", new AspectList().add(Aspect.SENSES, 10).add(Aspect.CRAFT, 5));
        ThaumcraftApi.registerEntityTag("Guardian", new AspectList().add(Aspect.BEAST, 10).add(Aspect.ELDRITCH, 10).add(Aspect.WATER, 10));
        ThaumcraftApi.registerEntityTag("Guardian", new AspectList().add(Aspect.BEAST, 10).add(Aspect.ELDRITCH, 15).add(Aspect.WATER, 15), new ThaumcraftApi.EntityTagsNBT("Elder", true));
        ThaumcraftApi.registerEntityTag("Rabbit", new AspectList().add(Aspect.BEAST, 5).add(Aspect.EARTH, 5).add(Aspect.MOTION, 5));
        ThaumcraftApi.registerEntityTag("Endermite", new AspectList().add(Aspect.BEAST, 5).add(Aspect.ELDRITCH, 5).add(Aspect.MOTION, 5));
        ThaumcraftApi.registerEntityTag("PolarBear", new AspectList().add(Aspect.BEAST, 15).add(Aspect.COLD, 10));
        ThaumcraftApi.registerEntityTag("Shulker", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.TRAP, 5).add(Aspect.FLIGHT, 5).add(Aspect.PROTECT, 5));
        ThaumcraftApi.registerEntityTag("EvocationIllager", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.MAGIC, 5).add(Aspect.MAN, 10));
        ThaumcraftApi.registerEntityTag("VindicationIllager", new AspectList().add(Aspect.AVERSION, 5).add(Aspect.MAGIC, 5).add(Aspect.MAN, 10));
        ThaumcraftApi.registerEntityTag("IllusionIllager", new AspectList().add(Aspect.SENSES, 5).add(Aspect.MAGIC, 5).add(Aspect.MAN, 10));
        ThaumcraftApi.registerEntityTag("Llama", new AspectList().add(Aspect.BEAST, 15).add(Aspect.WATER, 5));
        ThaumcraftApi.registerEntityTag("Parrot", new AspectList().add(Aspect.BEAST, 5).add(Aspect.FLIGHT, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerEntityTag("Stray", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 5).add(Aspect.TRAP, 5));
        ThaumcraftApi.registerEntityTag("Vex", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.FLIGHT, 5).add(Aspect.MAGIC, 5).add(Aspect.MAN, 5));
        ThaumcraftApi.registerEntityTag("Stray", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 5).add(Aspect.TRAP, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.FluxRift", new AspectList().add(Aspect.FLUX, 20).add(Aspect.ELDRITCH, 20).add(Aspect.AURA, 20));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Firebat", new AspectList().add(Aspect.BEAST, 5).add(Aspect.FLIGHT, 5).add(Aspect.FIRE, 10));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", new AspectList().add(Aspect.MAN, 10).add(Aspect.AURA, 5).add(Aspect.EXCHANGE, 10).add(Aspect.DESIRE, 5), new ThaumcraftApi.EntityTagsNBT("PechType", 0));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", new AspectList().add(Aspect.MAN, 10).add(Aspect.AURA, 5).add(Aspect.EXCHANGE, 10).add(Aspect.AVERSION, 5), new ThaumcraftApi.EntityTagsNBT("PechType", 1));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", new AspectList().add(Aspect.MAN, 10).add(Aspect.AURA, 5).add(Aspect.EXCHANGE, 10).add(Aspect.MAGIC, 5), new ThaumcraftApi.EntityTagsNBT("PechType", 2));
        ThaumcraftApi.registerEntityTag("Thaumcraft.ThaumSlime", new AspectList().add(Aspect.LIFE, 5).add(Aspect.WATER, 5).add(Aspect.FLUX, 5).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.BrainyZombie", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 10).add(Aspect.MIND, 5).add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.GiantBrainyZombie", new AspectList().add(Aspect.UNDEAD, 25).add(Aspect.MAN, 15).add(Aspect.MIND, 5).add(Aspect.AVERSION, 10));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Taintacle", new AspectList().add(Aspect.FLUX, 15).add(Aspect.BEAST, 10));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSeed", new AspectList().add(Aspect.FLUX, 20).add(Aspect.AURA, 10).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSeedPrime", new AspectList().add(Aspect.FLUX, 25).add(Aspect.AURA, 15).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintacleTiny", new AspectList().add(Aspect.FLUX, 5).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSwarm", new AspectList().add(Aspect.FLUX, 15).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.MindSpider", new AspectList().add(Aspect.FLUX, 5).add(Aspect.FIRE, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchGuardian", new AspectList().add(Aspect.ELDRITCH, 20).add(Aspect.DEATH, 20).add(Aspect.UNDEAD, 20));
        ThaumcraftApi.registerEntityTag("Thaumcraft.CultistKnight", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.MAN, 15).add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.CultistCleric", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.MAN, 15).add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchCrab", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.BEAST, 10).add(Aspect.TRAP, 10));
        ThaumcraftApi.registerEntityTag("Thaumcraft.InhabitedZombie", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.UNDEAD, 10).add(Aspect.MAN, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSeed", new AspectList().add(Aspect.PLANT, 20).add(Aspect.BEAST, 20).add(Aspect.FLUX, 20));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSeedPrime", new AspectList().add(Aspect.PLANT, 30).add(Aspect.BEAST, 30).add(Aspect.FLUX, 30));
        ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchWarden", new AspectList().add(Aspect.ELDRITCH, 40).add(Aspect.DEATH, 40).add(Aspect.UNDEAD, 40));
        ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchGolem", new AspectList().add(Aspect.ELDRITCH, 40).add(Aspect.ENERGY, 40).add(Aspect.MECHANISM, 40));
        ThaumcraftApi.registerEntityTag("Thaumcraft.CultistLeader", new AspectList().add(Aspect.ELDRITCH, 40).add(Aspect.AVERSION, 40).add(Aspect.MAN, 40));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintacleGiant", new AspectList().add(Aspect.ELDRITCH, 40).add(Aspect.BEAST, 40).add(Aspect.FLUX, 40));
        for (Aspect tag : Aspect.aspects.values()) {
            ThaumcraftApi.registerEntityTag("Thaumcraft.Wisp", new AspectList().add(tag, 5).add(Aspect.AURA, 5).add(Aspect.FLIGHT, 5), new ThaumcraftApi.EntityTagsNBT("Type", tag.getTag()));
        }
        ThaumcraftApi.registerEntityTag("Thaumcraft.Golem", new AspectList().add(Aspect.MECHANISM, 10).add(Aspect.MAN, 10).add(Aspect.MOTION, 10));
    }
    
    private static void registerItemAspects() {
        ThaumcraftApi.registerObjectTag("oreLapis", new AspectList().add(Aspect.EARTH, 5).add(Aspect.SENSES, 15));
        ThaumcraftApi.registerObjectTag("oreDiamond", new AspectList().add(Aspect.EARTH, 5).add(Aspect.DESIRE, 15).add(Aspect.CRYSTAL, 15));
        ThaumcraftApi.registerObjectTag("gemDiamond", new AspectList().add(Aspect.CRYSTAL, 15).add(Aspect.DESIRE, 15));
        ThaumcraftApi.registerObjectTag("oreRedstone", new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENERGY, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.LIT_REDSTONE_ORE), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENERGY, 15));
        ThaumcraftApi.registerObjectTag("oreEmerald", new AspectList().add(Aspect.EARTH, 5).add(Aspect.DESIRE, 10).add(Aspect.CRYSTAL, 15));
        ThaumcraftApi.registerObjectTag("gemEmerald", new AspectList().add(Aspect.CRYSTAL, 15).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("oreQuartz", new AspectList().add(Aspect.EARTH, 5).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag("gemQuartz", new AspectList().add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag("oreIron", new AspectList().add(Aspect.EARTH, 5).add(Aspect.METAL, 15));
        ThaumcraftApi.registerObjectTag("dustIron", new AspectList().add(Aspect.METAL, 15).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag("ingotIron", new AspectList().add(Aspect.METAL, 15));
        ThaumcraftApi.registerObjectTag("oreGold", new AspectList().add(Aspect.EARTH, 5).add(Aspect.METAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("dustGold", new AspectList().add(Aspect.METAL, 10).add(Aspect.DESIRE, 10).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag("ingotGold", new AspectList().add(Aspect.METAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.COAL_ORE), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENERGY, 15).add(Aspect.FIRE, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.COAL, 1, 32767), new AspectList().add(Aspect.ENERGY, 10).add(Aspect.FIRE, 10));
        ThaumcraftApi.registerObjectTag("dustRedstone", new AspectList().add(Aspect.ENERGY, 10));
        ThaumcraftApi.registerObjectTag("dustGlowstone", new AspectList().add(Aspect.SENSES, 5).add(Aspect.LIGHT, 10));
        ThaumcraftApi.registerObjectTag("glowstone", new AspectList(new ItemStack(Blocks.GLOWSTONE)));
        ThaumcraftApi.registerObjectTag("ingotCopper", new AspectList().add(Aspect.METAL, 10).add(Aspect.EXCHANGE, 5));
        ThaumcraftApi.registerObjectTag("dustCopper", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.EXCHANGE, 5));
        ThaumcraftApi.registerObjectTag("oreCopper", new AspectList().add(Aspect.METAL, 10).add(Aspect.EARTH, 5).add(Aspect.EXCHANGE, 5));
        ThaumcraftApi.registerObjectTag("clusterCopper", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.EXCHANGE, 10));
        ThaumcraftApi.registerObjectTag("ingotTin", new AspectList().add(Aspect.METAL, 10).add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag("dustTin", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag("oreTin", new AspectList().add(Aspect.METAL, 10).add(Aspect.EARTH, 5).add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag("clusterTin", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag("ingotSilver", new AspectList().add(Aspect.METAL, 10).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerObjectTag("dustSilver", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerObjectTag("oreSilver", new AspectList().add(Aspect.METAL, 10).add(Aspect.EARTH, 5).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerObjectTag("clusterSilver", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("ingotLead", new AspectList().add(Aspect.METAL, 10).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("dustLead", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("oreLead", new AspectList().add(Aspect.METAL, 10).add(Aspect.EARTH, 5).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("clusterLead", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.ORDER, 10));
        ThaumcraftApi.registerObjectTag("ingotBrass", new AspectList().add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("dustBrass", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("ingotBronze", new AspectList().add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("dustBronze", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("oreUranium", new AspectList().add(Aspect.METAL, 10).add(Aspect.DEATH, 5).add(Aspect.ENERGY, 10));
        ThaumcraftApi.registerObjectTag("itemDropUranium", new AspectList().add(Aspect.METAL, 10).add(Aspect.DEATH, 5).add(Aspect.ENERGY, 10));
        ThaumcraftApi.registerObjectTag("ingotUranium", new AspectList().add(Aspect.METAL, 10).add(Aspect.DEATH, 5).add(Aspect.ENERGY, 10));
        ThaumcraftApi.registerObjectTag("gemRuby", new AspectList().add(Aspect.CRYSTAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("gemGreenSapphire", new AspectList().add(Aspect.CRYSTAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("gemSapphire", new AspectList().add(Aspect.CRYSTAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("ingotSteel", new AspectList().add(Aspect.METAL, 15).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("itemRubber", new AspectList().add(Aspect.MOTION, 5).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("stone", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("stoneGranite", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("stoneDiorite", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("stoneAndesite", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("cobblestone", new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BEDROCK), new AspectList().add(Aspect.VOID, 25).add(Aspect.ENTROPY, 25).add(Aspect.EARTH, 25).add(Aspect.DARKNESS, 25));
        ThaumcraftApi.registerObjectTag("dirt", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DIRT, 1, 2), new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.FARMLAND, 1, 32767), new AspectList().add(Aspect.EARTH, 5).add(Aspect.WATER, 2).add(Aspect.ORDER, 2));
        ThaumcraftApi.registerObjectTag("sand", new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENTROPY, 5));
        ThaumcraftApi.registerObjectTag("grass", new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.GRASS_PATH), new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 2).add(Aspect.ORDER, 2));
        ThaumcraftApi.registerObjectTag("endstone", new AspectList().add(Aspect.EARTH, 5).add(Aspect.DARKNESS, 5));
        ThaumcraftApi.registerObjectTag("gravel", new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENTROPY, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MYCELIUM), new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 1).add(Aspect.FLUX, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.CLAY_BALL, 1, 32767), new AspectList().add(Aspect.WATER, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.HARDENED_CLAY, 1, 32767), new AspectList(new ItemStack(Blocks.CLAY)).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STAINED_HARDENED_CLAY, 1, 32767), new AspectList(new ItemStack(Blocks.CLAY)).add(Aspect.FIRE, 1).add(Aspect.SENSES, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.BRICK, 1, 32767), new AspectList(new ItemStack(Items.CLAY_BALL)).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag("netherrack", new AspectList().add(Aspect.EARTH, 5).add(Aspect.FIRE, 2));
        ThaumcraftApi.registerObjectTag("ingotBrickNether", new AspectList(new ItemStack(Blocks.NETHERRACK)).add(Aspect.FIRE, 1).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SOUL_SAND, 1, 32767), new AspectList().add(Aspect.EARTH, 3).add(Aspect.TRAP, 1).add(Aspect.SOUL, 3));
        ThaumcraftApi.registerObjectTag("blockGlass", new AspectList().add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MOSSY_COBBLESTONE, 1, 32767), new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 3).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag("obsidian", new AspectList().add(Aspect.EARTH, 5).add(Aspect.FIRE, 5).add(Aspect.DARKNESS, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STONEBRICK, 1, 1), new AspectList(new ItemStack(Blocks.STONEBRICK)).add(Aspect.PLANT, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STONEBRICK, 1, 2), new AspectList(new ItemStack(Blocks.STONEBRICK)).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.STONEBRICK, 1, 3), new AspectList(new ItemStack(Blocks.STONEBRICK)).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SANDSTONE, 1, 1), new AspectList(new ItemStack(Blocks.SANDSTONE)).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SANDSTONE, 1, 2), new AspectList(new ItemStack(Blocks.SANDSTONE)).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.CONCRETE, 1, 32767), new AspectList(new ItemStack(Blocks.CONCRETE_POWDER)).add(Aspect.WATER, 1).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BLACK_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BLUE_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BROWN_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.CYAN_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.GRAY_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.GREEN_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.LIME_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MAGENTA_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.ORANGE_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PINK_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PURPLE_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.RED_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SILVER_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WHITE_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.YELLOW_GLAZED_TERRACOTTA), new AspectList(new ItemStack(Blocks.STAINED_HARDENED_CLAY)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag("logWood", new AspectList().add(Aspect.PLANT, 20));
        ThaumcraftApi.registerObjectTag("treeSapling", new AspectList().add(Aspect.PLANT, 15).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag("treeLeaves", new AspectList().add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.TALLGRASS, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DOUBLE_PLANT, 1, 0), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1).add(Aspect.SENSES, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DOUBLE_PLANT, 1, 1), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1).add(Aspect.SENSES, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DOUBLE_PLANT, 1, 2), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DOUBLE_PLANT, 1, 3), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DOUBLE_PLANT, 1, 4), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1).add(Aspect.SENSES, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DOUBLE_PLANT, 1, 5), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1).add(Aspect.SENSES, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WATERLILY, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.WATER, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DEADBUSH, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag("vine", new AspectList().add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.WHEAT_SEEDS, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.MELON_SEEDS, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.PUMPKIN_SEEDS, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.BEETROOT_SEEDS, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag("cropNetherWart", new AspectList().add(Aspect.PLANT, 1).add(Aspect.FLUX, 2).add(Aspect.ALCHEMY, 3));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.RED_FLOWER, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.YELLOW_FLOWER, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerObjectTag("blockCactus", new AspectList().add(Aspect.PLANT, 5).add(Aspect.WATER, 5).add(Aspect.AVERSION, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BROWN_MUSHROOM), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DARKNESS, 2).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.RED_MUSHROOM), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DARKNESS, 2).add(Aspect.FIRE, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BROWN_MUSHROOM_BLOCK, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DARKNESS, 2).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.RED_MUSHROOM_BLOCK, 1, 32767), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DARKNESS, 2).add(Aspect.FIRE, 2));
        ThaumcraftApi.registerObjectTag("sugarcane", new AspectList().add(Aspect.PLANT, 5).add(Aspect.WATER, 3).add(Aspect.AIR, 2));
        ThaumcraftApi.registerObjectTag("cropWheat", new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.APPLE), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag("cropCarrot", new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerObjectTag("cropPotato", new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.BEETROOT), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5).add(Aspect.DESIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.BAKED_POTATO), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.POISONOUS_POTATO), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DEATH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PUMPKIN), new AspectList().add(Aspect.PLANT, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.MELON_BLOCK, 1, 32767), new AspectList().add(Aspect.PLANT, 10).remove(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.MELON), new AspectList().add(Aspect.PLANT, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SPONGE, 1, 0), new AspectList().add(Aspect.EARTH, 5).add(Aspect.TRAP, 5).add(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SPONGE, 1, 1), new AspectList().add(Aspect.EARTH, 5).add(Aspect.TRAP, 5).add(Aspect.WATER, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.SUGAR), new AspectList().add(Aspect.DESIRE, 1).add(Aspect.ENERGY, 1));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.CAKE), new AspectList().add(Aspect.DESIRE, 1).add(Aspect.LIFE, 2));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.PUMPKIN_PIE), new AspectList().add(Aspect.DESIRE, 1).add(Aspect.LIFE, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WOOL), new AspectList().add(Aspect.BEAST, 15).add(Aspect.CRAFT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.EXPERIENCE_BOTTLE), new AspectList().add(Aspect.MIND, 20));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.NAME_TAG, 1, 32767), new AspectList().add(Aspect.MIND, 10).add(Aspect.BEAST, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.IRON_HORSE_ARMOR, 1, 32767), new AspectList().add(Aspect.METAL, 15).add(Aspect.PROTECT, 10).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.GOLDEN_HORSE_ARMOR, 1, 32767), new AspectList().add(Aspect.METAL, 10).add(Aspect.PROTECT, 15).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.DIAMOND_HORSE_ARMOR, 1, 32767), new AspectList().add(Aspect.CRYSTAL, 15).add(Aspect.PROTECT, 20).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.FIRE, 1, 32767), new AspectList().add(Aspect.FIRE, 20));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MAGMA, 1, 32767), new AspectList().add(Aspect.FIRE, 10).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.CHORUS_FLOWER, 1, 32767), new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.SENSES, 5).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.CHORUS_PLANT, 1, 32767), new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHORUS_FRUIT), new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.SENSES, 5).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHORUS_FRUIT_POPPED), new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.SENSES, 5).add(Aspect.PLANT, 4).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.ICE, 1, 32767), new AspectList().add(Aspect.COLD, 20));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PACKED_ICE, 1, 32767), new AspectList().add(Aspect.COLD, 15).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SNOWBALL, 1, 32767), new AspectList().add(Aspect.COLD, 1));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.COOKIE, 1, 32767), new AspectList().add(Aspect.DESIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.POTIONITEM), new AspectList().add(Aspect.WATER, 5).add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.TORCH, 1, 32767), new AspectList().add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WEB, 1, 32767), new AspectList().add(Aspect.TRAP, 5).add(Aspect.BEAST, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.FLINT, 1, 32767), new AspectList().add(Aspect.EARTH, 5).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("string", new AspectList().add(Aspect.BEAST, 5).add(Aspect.CRAFT, 1));
        ThaumcraftApi.registerObjectTag("slimeball", new AspectList().add(Aspect.WATER, 5).add(Aspect.LIFE, 5).add(Aspect.ALCHEMY, 1));
        ThaumcraftApi.registerObjectTag("leather", new AspectList().add(Aspect.BEAST, 5).add(Aspect.PROTECT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.ROTTEN_FLESH, 1, 32767), new AspectList().add(Aspect.MAN, 5).add(Aspect.LIFE, 5).add(Aspect.ENTROPY, 5));
        ThaumcraftApi.registerObjectTag("feather", new AspectList().add(Aspect.FLIGHT, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerObjectTag("bone", new AspectList().add(Aspect.DEATH, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag("egg", new AspectList().add(Aspect.LIFE, 5).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SPIDER_EYE, 1, 32767), new AspectList().add(Aspect.SENSES, 5).add(Aspect.BEAST, 5).add(Aspect.DEATH, 5));
        ThaumcraftApi.registerObjectTag("gunpowder", new AspectList().add(Aspect.FIRE, 10).add(Aspect.ENTROPY, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.FISH, 1, 32767), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.WATER, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_FISH, 1, 32767), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHICKEN, 1, 32767), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_CHICKEN, 1, 32767), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.PORKCHOP, 1, 32767), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_PORKCHOP, 1, 32767), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.BEEF, 1, 32767), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_BEEF, 1, 32767), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.MUTTON, 1, 32767), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_MUTTON, 1, 32767), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RABBIT, 1, 32767), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.COOKED_RABBIT, 1, 32767), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RABBIT_HIDE, 1, 32767), new AspectList().add(Aspect.BEAST, 5).add(Aspect.PROTECT, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RABBIT_FOOT, 1, 32767), new AspectList().add(Aspect.BEAST, 5).add(Aspect.PROTECT, 5).add(Aspect.MOTION, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.BLAZE_ROD, 1, 32767), new AspectList().add(Aspect.FIRE, 15).add(Aspect.ENERGY, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SADDLE, 1, 32767), new AspectList().add(Aspect.BEAST, 10).add(Aspect.MOTION, 10).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("enderpearl", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.GHAST_TEAR, 1, 32767), new AspectList().add(Aspect.UNDEAD, 5).add(Aspect.SOUL, 10).add(Aspect.ALCHEMY, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 0), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.UNDEAD, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 1), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.UNDEAD, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 2), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.MAN, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 3), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.MAN, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 4), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.ENTROPY, 5).add(Aspect.FIRE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SKULL, 1, 5), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.FIRE, 10).add(Aspect.DARKNESS, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.DRAGON_BREATH), new AspectList().add(Aspect.DARKNESS, 10).add(Aspect.ENTROPY, 10).add(Aspect.FIRE, 10).add(Aspect.ALCHEMY, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.CAULDRON), new AspectList().add(Aspect.ALCHEMY, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.FERMENTED_SPIDER_EYE), new AspectList().add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BLAZE_POWDER), new AspectList().add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.SPECKLED_MELON), new AspectList().add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.MAGMA_CREAM), new AspectList().add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.TOTEM_OF_UNDYING), new AspectList().add(Aspect.ORDER, 10).add(Aspect.ENTROPY, 10).add(Aspect.LIFE, 25).add(Aspect.UNDEAD, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.SHULKER_SHELL), new AspectList().add(Aspect.PROTECT, 10).add(Aspect.ELDRITCH, 5).add(Aspect.BEAST, 5).add(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BLACK_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BLUE_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.GREEN_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.RED_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.YELLOW_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.SILVER_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.WHITE_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.ORANGE_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PINK_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.GRAY_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.CYAN_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.LIGHT_BLUE_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.LIME_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MAGENTA_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.BROWN_SHULKER_BOX), new AspectList(new ItemStack(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_11), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.DESIRE, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_13), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.WATER, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_CAT), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.BEAST, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_CHIRP), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.EARTH, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_FAR), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.ELDRITCH, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_MALL), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.MAN, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_MELLOHI), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.CRAFT, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_STAL), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.DARKNESS, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_STRAD), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.ENERGY, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_WARD), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.LIFE, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_BLOCKS), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.TOOL, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.RECORD_WAIT), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.TRAP, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("netherStar", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.MAGIC, 20).add(Aspect.ORDER, 20).add(Aspect.AURA, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHAINMAIL_HELMET, 1, 32767), new AspectList().add(Aspect.METAL, 42));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHAINMAIL_CHESTPLATE, 1, 32767), new AspectList().add(Aspect.METAL, 67));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHAINMAIL_LEGGINGS, 1, 32767), new AspectList().add(Aspect.METAL, 58));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.CHAINMAIL_BOOTS, 1, 32767), new AspectList().add(Aspect.METAL, 33));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.PAPER), new AspectList().add(Aspect.MIND, 2));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ENCHANTED_BOOK), new AspectList(new ItemStack(Items.BOOK)));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.BOOKSHELF), new AspectList().add(Aspect.MIND, 8));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.DRAGON_EGG), new AspectList().add(Aspect.ELDRITCH, 15).add(Aspect.BEAST, 15).add(Aspect.DARKNESS, 15).add(Aspect.MOTION, 15).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.PORTAL, 1, 32767), new AspectList().add(Aspect.FIRE, 10).add(Aspect.MOTION, 20).add(Aspect.MAGIC, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.END_PORTAL, 1, 32767), new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.MOTION, 20).add(Aspect.MAGIC, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.END_PORTAL_FRAME, 1, 32767), new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.ENERGY, 10).add(Aspect.MOTION, 10).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.MOB_SPAWNER, 1, 32767), new AspectList().add(Aspect.BEAST, 20).add(Aspect.MOTION, 20).add(Aspect.UNDEAD, 20).add(Aspect.MAGIC, 20));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.PRISMARINE_SHARD), new AspectList().add(Aspect.WATER, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.PRISMARINE_CRYSTALS), new AspectList().add(Aspect.WATER, 5).add(Aspect.CRYSTAL, 5).add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.ELYTRA), new AspectList().add(Aspect.FLIGHT, 20).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.END_ROD, 1, 32767), new AspectList().add(Aspect.FIRE, 1).add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.CHEST, 1, 32767), new AspectList().add(Aspect.VOID, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.TRAPPED_CHEST, 1, 32767), new AspectList().add(Aspect.TRAP, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ENDER_EYE), new AspectList().add(Aspect.SENSES, 10).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ARROW), new AspectList().add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.GLASS_BOTTLE), new AspectList().add(Aspect.VOID, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.GOLDEN_APPLE, 1, 0), new AspectList().add(Aspect.MAGIC, 5).add(Aspect.LIFE, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.GOLDEN_APPLE, 1, 1), new AspectList().add(Aspect.MAGIC, 5).add(Aspect.LIFE, 15).add(Aspect.PROTECT, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BOWL), new AspectList().add(Aspect.VOID, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.MUSHROOM_STEW), new AspectList().add(Aspect.LIFE, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.MINECART), new AspectList().add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.IRON_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ACACIA_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.DARK_OAK_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.JUNGLE_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.OAK_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.SPRUCE_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BIRCH_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.ACACIA_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BIRCH_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.DARK_OAK_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.JUNGLE_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.SPRUCE_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.FLINT_AND_STEEL, 1, 32767), new AspectList().add(Aspect.FIRE, 10).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.FISHING_ROD, 1, 32767), new AspectList().add(Aspect.WATER, 10).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.SHIELD, 1, 32767), new AspectList().add(Aspect.PROTECT, 20));
        for (int a = 0; a < 16; ++a) {
            ItemStack sis = new ItemStack(Items.SHIELD, 1, 32767);
            NBTTagCompound nbttagcompound = new NBTTagCompound();
            nbttagcompound.setInteger("Base", a);
            sis.setTagInfo("BlockEntityTag", nbttagcompound);
            ThaumcraftApi.registerComplexObjectTag(sis, new AspectList().merge(Aspect.PROTECT, 20));
        }
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.SPECTRAL_ARROW, 1, 32767), new AspectList().add(Aspect.SENSES, 10).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BUCKET), new AspectList().add(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ForgeModContainer.getInstance().universalBucket), new AspectList(new ItemStack(Items.BUCKET)));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.WATER_BUCKET), new AspectList(new ItemStack(Items.BUCKET)).add(Aspect.WATER, 20));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.LAVA_BUCKET), new AspectList(new ItemStack(Items.BUCKET)).add(Aspect.FIRE, 15).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.MILK_BUCKET), new AspectList(new ItemStack(Items.BUCKET)).add(Aspect.LIFE, 10).add(Aspect.BEAST, 5).add(Aspect.WATER, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.BREWING_STAND), new AspectList().add(Aspect.CRAFT, 15).add(Aspect.ALCHEMY, 25));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.STONE_BUTTON), new AspectList().add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.RAIL, 1, 32767), new AspectList().add(Aspect.MOTION, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DETECTOR_RAIL, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 1));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.GOLDEN_RAIL, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.ENERGY, 1));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.ACTIVATOR_RAIL, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.ACACIA_FENCE_GATE, 1, 32767), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DARK_OAK_FENCE_GATE, 1, 32767), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.JUNGLE_FENCE_GATE, 1, 32767), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DARK_OAK_FENCE_GATE, 1, 32767), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.SPRUCE_FENCE_GATE, 1, 32767), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.BIRCH_FENCE_GATE, 1, 32767), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.WOODEN_PRESSURE_PLATE, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.STONE_PRESSURE_PLATE, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.LEVER, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.PISTON, 1, 32767), new AspectList().add(Aspect.MECHANISM, 10).add(Aspect.MOTION, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.STICKY_PISTON, 1, 32767), new AspectList().add(Aspect.MECHANISM, 10).add(Aspect.MOTION, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.JUKEBOX), new AspectList().add(Aspect.SENSES, 20).add(Aspect.MECHANISM, 10).add(Aspect.AIR, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.NOTEBLOCK), new AspectList().add(Aspect.SENSES, 20).add(Aspect.MECHANISM, 10).add(Aspect.AIR, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.TRAPDOOR, 1, 32767), new AspectList().add(Aspect.MOTION, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.FURNACE, 1, 32767), new AspectList().add(Aspect.FIRE, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.ENCHANTING_TABLE), new AspectList().add(Aspect.MAGIC, 25).add(Aspect.CRAFT, 15));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.CRAFTING_TABLE), new AspectList().add(Aspect.CRAFT, 20));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.CLOCK), new AspectList().add(Aspect.MECHANISM, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.BEACON), new AspectList().add(Aspect.AURA, 10).add(Aspect.MAGIC, 10).add(Aspect.EXCHANGE, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.WOODEN_BUTTON, 1, 32767), new AspectList().add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.CARROT_ON_A_STICK, 1, 32767), new AspectList().add(Aspect.MOTION, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.FLOWER_POT), new AspectList().add(Aspect.VOID, 5).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.GOLDEN_CARROT), new AspectList().add(Aspect.SENSES, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.ENDER_CHEST, 1, 32767), new AspectList().merge(Aspect.EXCHANGE, 10).merge(Aspect.MOTION, 10).merge(Aspect.VOID, 20));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.COMPARATOR, 1, 32767), new AspectList().merge(Aspect.MECHANISM, 15).merge(Aspect.ORDER, 5).merge(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Items.REPEATER, 1, 32767), new AspectList().merge(Aspect.MECHANISM, 15).merge(Aspect.ENERGY, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.HOPPER, 1, 32767), new AspectList().merge(Aspect.MECHANISM, 5).merge(Aspect.EXCHANGE, 10).merge(Aspect.VOID, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DROPPER, 1, 32767), new AspectList().merge(Aspect.MECHANISM, 5).merge(Aspect.EXCHANGE, 10).merge(Aspect.VOID, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DISPENSER, 1, 32767), new AspectList().merge(Aspect.MECHANISM, 5).merge(Aspect.EXCHANGE, 10).merge(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(Blocks.TRIPWIRE_HOOK, 1, 32767), new AspectList().add(Aspect.SENSES, 5).add(Aspect.MECHANISM, 5).add(Aspect.TRAP, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.TRIPWIRE, 1, 32767), new AspectList().merge(Aspect.SENSES, 5).merge(Aspect.MECHANISM, 5).merge(Aspect.TRAP, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(Blocks.DAYLIGHT_DETECTOR, 1, 32767), new AspectList().merge(Aspect.SENSES, 10).merge(Aspect.LIGHT, 10).merge(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag("gear*", new AspectList().add(Aspect.MECHANISM, 5));
        for (PotionType potiontype : PotionType.REGISTRY) {
            ItemStack stack = PotionUtils.addPotionToItemStack(new ItemStack(Items.POTIONITEM), potiontype);
            ThaumcraftApi.registerObjectTag(stack, getPotionAspects(stack).add(Aspect.WATER, 5));
            ItemStack stack2 = PotionUtils.addPotionToItemStack(new ItemStack(Items.TIPPED_ARROW), potiontype);
            ThaumcraftApi.registerObjectTag(stack2, getPotionAspects(stack2).add(Aspect.AVERSION, 5));
            ItemStack stack3 = PotionUtils.addPotionToItemStack(new ItemStack(Items.SPLASH_POTION), potiontype);
            ThaumcraftApi.registerObjectTag(stack3, getPotionAspects(stack3).add(Aspect.ENERGY, 5));
            ItemStack stack4 = PotionUtils.addPotionToItemStack(new ItemStack(Items.LINGERING_POTION), potiontype);
            ThaumcraftApi.registerObjectTag(stack4, getPotionAspects(stack4).add(Aspect.TRAP, 5));
        }
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.DYE, 1, 0), new AspectList().add(Aspect.WATER, 2).add(Aspect.BEAST, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.DYE, 1, 2), new AspectList(new ItemStack(Blocks.CACTUS)).add(Aspect.WATER, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.DYE, 1, 3), new AspectList().add(Aspect.DESIRE, 2).add(Aspect.ENERGY, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.DYE, 1, 4), new AspectList().add(Aspect.EARTH, 2).add(Aspect.DESIRE, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(Items.DYE, 1, 15), new AspectList().add(Aspect.LIFE, 2).add(Aspect.DEATH, 1).add(Aspect.PLANT, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.phial, 1, 0), new AspectList().add(Aspect.VOID, 3));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.phial, 1, 1), new AspectList());
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.grassAmbient), new AspectList(new ItemStack(Blocks.GRASS)).add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(BlocksTC.tableWood), new AspectList().add(Aspect.TOOL, 1));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(BlocksTC.tableStone), new AspectList().add(Aspect.TOOL, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.arcaneWorkbench), new AspectList(new ItemStack(Blocks.CRAFTING_TABLE)).add(Aspect.MAGIC, 5).add(Aspect.AURA, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.tripleMeatTreat), new AspectList().add(Aspect.LIFE, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(FluidUtil.getFilledBucket(new FluidStack(ConfigBlocks.FluidPure.instance, 1000)), new AspectList(new ItemStack(Items.BUCKET)).add(Aspect.MIND, 15).add(Aspect.ORDER, 15));
        ThaumcraftApi.registerObjectTag(FluidUtil.getFilledBucket(new FluidStack(ConfigBlocks.FluidDeath.instance, 1000)), new AspectList(new ItemStack(Items.BUCKET)).add(Aspect.DEATH, 15).add(Aspect.ENTROPY, 15));
        ThaumcraftApi.registerObjectTag("clusterIron", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("clusterGold", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("clusterCinnabar", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.ALCHEMY, 5).add(Aspect.DEATH, 5));
        ThaumcraftApi.registerObjectTag("clusterQuartz", new AspectList().add(Aspect.ORDER, 5).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag("oreCinnabar", new AspectList().add(Aspect.EARTH, 5).add(Aspect.METAL, 10).add(Aspect.ALCHEMY, 5).add(Aspect.DEATH, 5));
        ThaumcraftApi.registerObjectTag("oreAmber", new AspectList().add(Aspect.EARTH, 5).add(Aspect.TRAP, 10).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag("quicksilver", new AspectList().add(Aspect.METAL, 10).add(Aspect.DEATH, 5).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerObjectTag("gemAmber", new AspectList().add(Aspect.TRAP, 10).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.nuggets, 1, 10), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ORDER, 5).add(Aspect.METAL, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.crystalAir, 1, 32767), new AspectList().add(Aspect.AIR, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.crystalFire, 1, 32767), new AspectList().add(Aspect.FIRE, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.crystalWater, 1, 32767), new AspectList().add(Aspect.WATER, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.crystalEarth, 1, 32767), new AspectList().add(Aspect.EARTH, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.crystalOrder, 1, 32767), new AspectList().add(Aspect.ORDER, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.crystalEntropy, 1, 32767), new AspectList().add(Aspect.ENTROPY, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.crystalTaint, 1, 32767), new AspectList().add(Aspect.FLUX, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.taintFibre), new AspectList().add(Aspect.PLANT, 5).add(Aspect.FLUX, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.taintCrust), new AspectList().add(Aspect.LIFE, 5).add(Aspect.FLUX, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.taintSoil), new AspectList().add(Aspect.EARTH, 5).add(Aspect.FLUX, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.taintGeyser), new AspectList().add(Aspect.AURA, 5).add(Aspect.WATER, 5).add(Aspect.FLUX, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.taintRock), new AspectList().add(Aspect.EARTH, 10).add(Aspect.FLUX, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.taintFeature, 1, 0), new AspectList().add(Aspect.AURA, 5).add(Aspect.BEAST, 5).add(Aspect.FLUX, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.taintLog, 1, 0), new AspectList().add(Aspect.PLANT, 5).add(Aspect.FLUX, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.logGreatwood), new AspectList().add(Aspect.PLANT, 20).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.logSilverwood), new AspectList().add(Aspect.PLANT, 20).add(Aspect.AURA, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.leafGreatwood), new AspectList().add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.leafSilverwood), new AspectList().add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.saplingGreatwood), new AspectList().add(Aspect.PLANT, 15).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.saplingSilverwood), new AspectList().add(Aspect.PLANT, 15).add(Aspect.AURA, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.shimmerleaf), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AURA, 10).add(Aspect.ENERGY, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.cinderpearl), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AURA, 5).add(Aspect.FIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.vishroom), new AspectList().add(Aspect.PLANT, 2).add(Aspect.DEATH, 1).add(Aspect.MAGIC, 1).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.stoneAncient), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.stoneAncientTile), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.stoneAncientRock), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.stoneEldritchTile), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.stoneAncientDoorway), new AspectList().add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 5).add(Aspect.TRAP, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.stoneAncientGlyphed), new AspectList().add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 5).add(Aspect.MIND, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.stonePorous), new AspectList().add(Aspect.EARTH, 5).add(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.researchTable, 1, 32767), new AspectList(new ItemStack(BlocksTC.tableWood)).add(Aspect.MIND, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.brain), new AspectList().add(Aspect.LIFE, 5).add(Aspect.MIND, 20).add(Aspect.UNDEAD, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.lootBag, 1, 0), new AspectList().add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.lootBag, 1, 1), new AspectList().add(Aspect.DESIRE, 20));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.lootBag, 1, 2), new AspectList().add(Aspect.DESIRE, 30));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.lootUrnCommon), new AspectList().add(Aspect.DESIRE, 10).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.lootUrnUncommon), new AspectList().add(Aspect.DESIRE, 20).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.lootUrnRare), new AspectList().add(Aspect.DESIRE, 30).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.lootCrateCommon), new AspectList().add(Aspect.DESIRE, 10).add(Aspect.PLANT, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.lootCrateUncommon), new AspectList().add(Aspect.DESIRE, 20).add(Aspect.PLANT, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.lootCrateRare), new AspectList().add(Aspect.DESIRE, 30).add(Aspect.PLANT, 2));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.chunks, 1, 32767), new AspectList().add(Aspect.LIFE, 5).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.salisMundus), new AspectList().add(Aspect.MAGIC, 5).add(Aspect.ENERGY, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.crucible), new AspectList(new ItemStack(Items.CAULDRON, 1, 32767)).add(Aspect.CRAFT, 20).add(Aspect.ALCHEMY, 20));
        for (Block ca : BlocksTC.candles.values()) {
            ThaumcraftApi.registerComplexObjectTag(new ItemStack(ca), new AspectList().add(Aspect.LIGHT, 5));
        }
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.thaumonomicon, 1, 32767), new AspectList(new ItemStack(Blocks.BOOKSHELF)).merge(Aspect.MAGIC, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(BlocksTC.pedestalArcane, 1, 0), new AspectList().add(Aspect.MAGIC, 3).add(Aspect.AIR, 3));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(BlocksTC.pedestalAncient, 1, 1), new AspectList().add(Aspect.MAGIC, 3).add(Aspect.ELDRITCH, 3));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(BlocksTC.pedestalEldritch, 1, 2), new AspectList().add(Aspect.MAGIC, 3).add(Aspect.ELDRITCH, 3));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(ItemsTC.thaumometer, 1, 32767), new AspectList().add(Aspect.SENSES, 10).add(Aspect.AURA, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(ItemsTC.goggles, 1, 32767), new AspectList().merge(Aspect.SENSES, 10).merge(Aspect.AURA, 10));
        ThaumcraftApi.registerComplexObjectTag(new ItemStack(BlocksTC.arcaneEar), new AspectList().add(Aspect.SENSES, 20));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.amuletVis, 1, 0), new AspectList().add(Aspect.AURA, 20).add(Aspect.METAL, 5).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.baubles, 1, 3), new AspectList().add(Aspect.AURA, 5).add(Aspect.METAL, 5).add(Aspect.MAGIC, 20));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonPlateChest, 1, 32767), new AspectList(new ItemStack(Items.IRON_CHESTPLATE)).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonPraetorChest, 1, 32767), new AspectList(new ItemStack(Items.IRON_CHESTPLATE)).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonRobeChest, 1, 32767), new AspectList(new ItemStack(Items.LEATHER_CHESTPLATE)).add(Aspect.MAGIC, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonPlateLegs, 1, 32767), new AspectList(new ItemStack(Items.IRON_LEGGINGS)).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonPraetorLegs, 1, 32767), new AspectList(new ItemStack(Items.IRON_LEGGINGS)).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonRobeLegs, 1, 32767), new AspectList(new ItemStack(Items.LEATHER_LEGGINGS)).add(Aspect.MAGIC, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonPlateHelm, 1, 32767), new AspectList(new ItemStack(Items.IRON_HELMET)).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonPraetorHelm, 1, 32767), new AspectList(new ItemStack(Items.IRON_HELMET)).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonRobeHelm, 1, 32767), new AspectList(new ItemStack(Items.LEATHER_HELMET)).add(Aspect.MAGIC, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonBoots, 1, 32767), new AspectList(new ItemStack(Items.IRON_BOOTS)).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.crimsonBlade, 1, 32767), new AspectList(new ItemStack(Items.IRON_SWORD)).add(Aspect.ELDRITCH, 10).add(Aspect.DEATH, 10));
        for (Block ca : BlocksTC.banners.values()) {
            ThaumcraftApi.registerComplexObjectTag(new ItemStack(ca), new AspectList().add(Aspect.ELDRITCH, 5));
        }
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.eldritchEye), new AspectList().add(Aspect.ELDRITCH, 15).add(Aspect.AURA, 15).add(Aspect.SENSES, 15).add(Aspect.SOUL, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.curio, 1, 0), new AspectList().add(Aspect.MIND, 15).add(Aspect.MAGIC, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.curio, 1, 1), new AspectList().add(Aspect.MIND, 15).add(Aspect.BEAST, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.curio, 1, 2), new AspectList().add(Aspect.MIND, 15).add(Aspect.DEATH, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.curio, 1, 3), new AspectList().add(Aspect.MIND, 15).add(Aspect.ELDRITCH, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.curio, 1, 4), new AspectList().add(Aspect.MIND, 30));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.curio, 1, 5), new AspectList().add(Aspect.MIND, 15).add(Aspect.FLUX, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.curio, 1, 6), new AspectList().add(Aspect.MIND, 15).add(Aspect.ELDRITCH, 5).add(Aspect.SOUL, 5).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.runedTablet), new AspectList().add(Aspect.TRAP, 15).add(Aspect.MIND, 15).add(Aspect.MECHANISM, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.celestialNotes, 1, 32767), new AspectList().add(Aspect.MIND, 5).add(Aspect.DARKNESS, 5).add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerObjectTag(new ItemStack(ItemsTC.primordialPearl, 1, 32767), new AspectList().add(Aspect.AIR, 10).add(Aspect.FIRE, 10).add(Aspect.WATER, 10).add(Aspect.EARTH, 10).add(Aspect.ORDER, 10).add(Aspect.ENTROPY, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.eldritch, 1, 0), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.eldritch, 1, 1), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.eldritch, 1, 2), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.eldritch, 1, 3), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.eldritch, 1, 4), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10).add(Aspect.MECHANISM, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.eldritch, 1, 5), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.eldritch, 1, 6), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerObjectTag(new ItemStack(BlocksTC.eldritch, 1, 7), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10).add(Aspect.BEAST, 15));
    }
    
    public static AspectList getPotionAspects(ItemStack itemstack) {
        AspectList tmp = new AspectList();
        boolean didit = false;
        PotionType potion = PotionUtils.getPotionFromItem(itemstack);
        if (potion != PotionTypes.WATER) {
            HashSet<ItemStack> hs = new HashSet<ItemStack>();
            ThaumcraftCraftingManager.getPotionReagentsRecursive(potion, hs);
            for (ItemStack his : hs) {
                AspectList tmp2 = ThaumcraftCraftingManager.getObjectTags(his);
                for (Aspect a : tmp2.aspects.keySet()) {
                    tmp.add(a, tmp2.getAmount(a));
                }
                didit = true;
                tmp.add(Aspect.ALCHEMY, 3);
            }
            try {
                for (Aspect a2 : tmp.aspects.keySet().toArray(new Aspect[0])) {
                    int amt = tmp.getAmount(a2);
                    tmp.remove(a2, (int)(amt * 0.66));
                }
            }
            catch (Exception ex) {}
            if (!didit) {
                tmp.add(Aspect.MAGIC, 5);
                tmp.add(Aspect.ALCHEMY, 5);
            }
        }
        else {
            tmp.add(Aspect.WATER, 5);
        }
        return tmp;
    }
    
    static {
        ConfigAspects.dyes = new String[] { "dyeBlack", "dyeRed", "dyeGreen", "dyeBrown", "dyeBlue", "dyePurple", "dyeCyan", "dyeLightGray", "dyeGray", "dyePink", "dyeLime", "dyeYellow", "dyeLightBlue", "dyeMagenta", "dyeOrange", "dyeWhite" };
    }
}
