// 
// Decompiled by Procyon v0.6.0
// 

package thaumcraft.client.renderers.models.gear;

import org.lwjgl.opengl.GL11;
import net.minecraft.util.math.MathHelper;
import net.minecraft.entity.Entity;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelKnightArmor extends ModelCustomArmor
{
    ModelRenderer Frontcloth1;
    ModelRenderer Helmet;
    ModelRenderer BeltR;
    ModelRenderer Mbelt;
    ModelRenderer MbeltL;
    ModelRenderer MbeltR;
    ModelRenderer BeltL;
    ModelRenderer Chestplate;
    ModelRenderer CloakAtL;
    ModelRenderer Backplate;
    ModelRenderer Cloak3;
    ModelRenderer CloakAtR;
    ModelRenderer Tabbard;
    ModelRenderer Cloak1;
    ModelRenderer Cloak2;
    ModelRenderer ShoulderR1;
    ModelRenderer GauntletR;
    ModelRenderer GauntletstrapR1;
    ModelRenderer GauntletstrapR2;
    ModelRenderer ShoulderR;
    ModelRenderer ShoulderR0;
    ModelRenderer ShoulderR2;
    ModelRenderer ShoulderL1;
    ModelRenderer GauntletL;
    ModelRenderer GauntletstrapL1;
    ModelRenderer GauntletstrapL2;
    ModelRenderer ShoulderL;
    ModelRenderer ShoulderL0;
    ModelRenderer ShoulderL2;
    ModelRenderer SidepanelR3;
    ModelRenderer SidepanelR2;
    ModelRenderer SidepanelL2;
    ModelRenderer SidepanelR0;
    ModelRenderer SidepanelL0;
    ModelRenderer SidepanelR1;
    ModelRenderer SidepanelL3;
    ModelRenderer Frontcloth2;
    ModelRenderer SidepanelL1;
    
    public ModelKnightArmor(final float f) {
        super(f, 0, 128, 64);
        this.textureWidth = 128;
        this.textureHeight = 64;
        (this.Helmet = new ModelRenderer(this, 41, 8)).addBox(-4.5f, -9.0f, -4.5f, 9, 9, 9);
        this.Helmet.setTextureSize(128, 64);
        this.setRotation(this.Helmet, 0.0f, 0.0f, 0.0f);
        (this.BeltR = new ModelRenderer(this, 76, 44)).addBox(-5.0f, 4.0f, -3.0f, 1, 3, 6);
        this.BeltR.setTextureSize(128, 64);
        this.setRotation(this.BeltR, 0.0f, 0.0f, 0.0f);
        (this.Mbelt = new ModelRenderer(this, 56, 55)).addBox(-4.0f, 8.0f, -3.0f, 8, 4, 1);
        this.Mbelt.setTextureSize(128, 64);
        this.setRotation(this.Mbelt, 0.0f, 0.0f, 0.0f);
        (this.MbeltL = new ModelRenderer(this, 76, 44)).addBox(4.0f, 8.0f, -3.0f, 1, 3, 6);
        this.MbeltL.setTextureSize(128, 64);
        this.setRotation(this.MbeltL, 0.0f, 0.0f, 0.0f);
        (this.MbeltR = new ModelRenderer(this, 76, 44)).addBox(-5.0f, 8.0f, -3.0f, 1, 3, 6);
        this.MbeltR.setTextureSize(128, 64);
        this.setRotation(this.MbeltR, 0.0f, 0.0f, 0.0f);
        (this.BeltL = new ModelRenderer(this, 76, 44)).addBox(4.0f, 4.0f, -3.0f, 1, 3, 6);
        this.BeltL.setTextureSize(128, 64);
        this.setRotation(this.BeltL, 0.0f, 0.0f, 0.0f);
        (this.Tabbard = new ModelRenderer(this, 114, 52)).addBox(-3.0f, 1.2f, -3.5f, 6, 10, 1);
        this.Tabbard.setTextureSize(128, 64);
        this.setRotation(this.Tabbard, 0.0f, 0.0f, 0.0f);
        (this.CloakAtL = new ModelRenderer(this, 0, 43)).addBox(2.5f, 1.0f, 2.0f, 2, 1, 3);
        this.CloakAtL.setTextureSize(128, 64);
        this.setRotation(this.CloakAtL, 0.1396263f, 0.0f, 0.0f);
        (this.Backplate = new ModelRenderer(this, 36, 45)).addBox(-4.0f, 1.0f, 2.0f, 8, 11, 2);
        this.Backplate.setTextureSize(128, 64);
        this.setRotation(this.Backplate, 0.0f, 0.0f, 0.0f);
        (this.Cloak1 = new ModelRenderer(this, 0, 47)).addBox(0.0f, 0.0f, 0.0f, 9, 12, 1);
        this.Cloak1.setRotationPoint(-4.5f, 1.3f, 4.2f);
        this.Cloak1.setTextureSize(128, 64);
        this.setRotation(this.Cloak1, 0.1396263f, 0.0f, 0.0f);
        (this.Cloak2 = new ModelRenderer(this, 0, 59)).addBox(0.0f, 11.7f, -2.0f, 9, 4, 1);
        this.Cloak2.setRotationPoint(-4.5f, 1.3f, 4.2f);
        this.Cloak2.setTextureSize(128, 64);
        this.setRotation(this.Cloak2, 0.3069452f, 0.0f, 0.0f);
        (this.Cloak3 = new ModelRenderer(this, 0, 59)).addBox(0.0f, 15.2f, -4.2f, 9, 4, 1);
        this.Cloak3.setRotationPoint(-4.5f, 1.3f, 4.2f);
        this.Cloak3.setTextureSize(128, 64);
        this.setRotation(this.Cloak3, 0.4465716f, 0.0f, 0.0f);
        (this.CloakAtR = new ModelRenderer(this, 0, 43)).addBox(-4.5f, 1.0f, 2.0f, 2, 1, 3);
        this.CloakAtR.setTextureSize(128, 64);
        this.setRotation(this.CloakAtR, 0.1396263f, 0.0f, 0.0f);
        (this.Chestplate = new ModelRenderer(this, 56, 45)).addBox(-4.0f, 1.0f, -3.0f, 8, 7, 1);
        this.Chestplate.setTextureSize(128, 64);
        this.setRotation(this.Chestplate, 0.0f, 0.0f, 0.0f);
        (this.ShoulderR1 = new ModelRenderer(this, 0, 19)).addBox(-3.3f, 3.5f, -2.5f, 1, 1, 5);
        this.ShoulderR1.setTextureSize(128, 64);
        this.setRotation(this.ShoulderR1, 0.0f, 0.0f, 0.7853982f);
        (this.GauntletR = new ModelRenderer(this, 100, 26)).addBox(-3.5f, 3.5f, -2.5f, 2, 6, 5);
        this.GauntletR.setTextureSize(128, 64);
        this.GauntletR.mirror = true;
        this.setRotation(this.GauntletR, 0.0f, 0.0f, 0.0f);
        (this.GauntletstrapR1 = new ModelRenderer(this, 84, 31)).addBox(-1.5f, 3.5f, -2.5f, 3, 1, 5);
        this.GauntletstrapR1.setTextureSize(128, 64);
        this.GauntletstrapR1.mirror = true;
        this.setRotation(this.GauntletstrapR1, 0.0f, 0.0f, 0.0f);
        (this.GauntletstrapR2 = new ModelRenderer(this, 84, 31)).addBox(-1.5f, 6.5f, -2.5f, 3, 1, 5);
        this.GauntletstrapR2.setTextureSize(128, 64);
        this.GauntletstrapR2.mirror = true;
        this.setRotation(this.GauntletstrapR2, 0.0f, 0.0f, 0.0f);
        (this.ShoulderR = new ModelRenderer(this, 56, 35)).addBox(-3.5f, -2.5f, -2.5f, 5, 5, 5);
        this.ShoulderR.setTextureSize(128, 64);
        this.ShoulderR.mirror = true;
        this.setRotation(this.ShoulderR, 0.0f, 0.0f, 0.0f);
        (this.ShoulderR0 = new ModelRenderer(this, 0, 0)).addBox(-4.3f, -1.5f, -3.0f, 3, 5, 6);
        this.ShoulderR0.setTextureSize(128, 64);
        this.ShoulderR0.mirror = true;
        this.setRotation(this.ShoulderR0, 0.0f, 0.0f, 0.7853982f);
        (this.ShoulderR2 = new ModelRenderer(this, 0, 11)).addBox(-2.3f, 3.5f, -3.0f, 1, 2, 6);
        this.ShoulderR2.setTextureSize(128, 64);
        this.ShoulderR2.mirror = true;
        this.setRotation(this.ShoulderR2, 0.0f, 0.0f, 0.7853982f);
        this.ShoulderL1 = new ModelRenderer(this, 0, 19);
        this.ShoulderL1.mirror = true;
        this.ShoulderL1.addBox(2.3f, 3.5f, -2.5f, 1, 1, 5);
        this.ShoulderL1.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL1, 0.0f, 0.0f, -0.7853982f);
        (this.GauntletL = new ModelRenderer(this, 114, 26)).addBox(1.5f, 3.5f, -2.5f, 2, 6, 5);
        this.GauntletL.setTextureSize(128, 64);
        this.setRotation(this.GauntletL, 0.0f, 0.0f, 0.0f);
        this.GauntletstrapL1 = new ModelRenderer(this, 84, 31);
        this.GauntletstrapL1.mirror = true;
        this.GauntletstrapL1.addBox(-1.5f, 3.5f, -2.5f, 3, 1, 5);
        this.GauntletstrapL1.setTextureSize(128, 64);
        this.setRotation(this.GauntletstrapL1, 0.0f, 0.0f, 0.0f);
        this.GauntletstrapL2 = new ModelRenderer(this, 84, 31);
        this.GauntletstrapL2.mirror = true;
        this.GauntletstrapL2.addBox(-1.5f, 6.5f, -2.5f, 3, 1, 5);
        this.GauntletstrapL2.setTextureSize(128, 64);
        this.setRotation(this.GauntletstrapL2, 0.0f, 0.0f, 0.0f);
        (this.ShoulderL = new ModelRenderer(this, 56, 35)).addBox(-1.5f, -2.5f, -2.5f, 5, 5, 5);
        this.ShoulderL.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL, 0.0f, 0.0f, 0.0f);
        (this.ShoulderL0 = new ModelRenderer(this, 0, 0)).addBox(1.3f, -1.5f, -3.0f, 3, 5, 6);
        this.ShoulderL0.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL0, 0.0f, 0.0f, -0.7853982f);
        (this.ShoulderL2 = new ModelRenderer(this, 0, 11)).addBox(1.3f, 3.5f, -3.0f, 1, 2, 6);
        this.ShoulderL2.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL2, 0.0f, 0.0f, -0.7853982f);
        (this.SidepanelR3 = new ModelRenderer(this, 116, 13)).addBox(-3.0f, 2.5f, -2.5f, 1, 4, 5);
        this.SidepanelR3.setTextureSize(128, 64);
        this.setRotation(this.SidepanelR3, 0.0f, 0.0f, 0.1396263f);
        this.SidepanelR2 = new ModelRenderer(this, 114, 5);
        this.SidepanelR2.mirror = true;
        this.SidepanelR2.addBox(-2.0f, 2.5f, -2.5f, 2, 3, 5);
        this.SidepanelR2.setTextureSize(128, 64);
        this.setRotation(this.SidepanelR2, 0.0f, 0.0f, 0.1396263f);
        (this.SidepanelL2 = new ModelRenderer(this, 114, 5)).addBox(0.0f, 2.5f, -2.5f, 2, 3, 5);
        this.SidepanelL2.setTextureSize(128, 64);
        this.setRotation(this.SidepanelL2, 0.0f, 0.0f, -0.1396263f);
        (this.SidepanelR0 = new ModelRenderer(this, 96, 14)).addBox(-3.0f, -0.5f, -2.5f, 5, 3, 5);
        this.SidepanelR0.setTextureSize(128, 64);
        this.setRotation(this.SidepanelR0, 0.0f, 0.0f, 0.1396263f);
        (this.SidepanelL0 = new ModelRenderer(this, 96, 14)).addBox(-2.0f, -0.5f, -2.5f, 5, 3, 5);
        this.SidepanelL0.setTextureSize(128, 64);
        this.setRotation(this.SidepanelL0, 0.0f, 0.0f, -0.1396263f);
        this.SidepanelR1 = new ModelRenderer(this, 96, 7);
        this.SidepanelR1.mirror = true;
        this.SidepanelR1.addBox(0.0f, 2.5f, -2.5f, 2, 2, 5);
        this.SidepanelR1.setTextureSize(128, 64);
        this.setRotation(this.SidepanelR1, 0.0f, 0.0f, 0.1396263f);
        (this.SidepanelL3 = new ModelRenderer(this, 116, 13)).addBox(2.0f, 2.5f, -2.5f, 1, 4, 5);
        this.SidepanelL3.setTextureSize(128, 64);
        this.setRotation(this.SidepanelL3, 0.0f, 0.0f, -0.1396263f);
        (this.SidepanelL1 = new ModelRenderer(this, 96, 7)).addBox(-2.0f, 2.5f, -2.5f, 2, 2, 5);
        this.SidepanelL1.setTextureSize(128, 64);
        this.setRotation(this.SidepanelL1, 0.0f, 0.0f, -0.1396263f);
        (this.Frontcloth1 = new ModelRenderer(this, 120, 39)).addBox(0.0f, 0.0f, 0.0f, 6, 8, 1);
        this.Frontcloth1.setRotationPoint(-3.0f, 11.0f, -3.5f);
        this.Frontcloth1.setTextureSize(128, 64);
        this.setRotation(this.Frontcloth1, -0.1047198f, 0.0f, 0.0f);
        (this.Frontcloth2 = new ModelRenderer(this, 100, 37)).addBox(0.0f, 7.5f, 1.8f, 6, 3, 1);
        this.Frontcloth2.setRotationPoint(-3.0f, 11.0f, -3.5f);
        this.Frontcloth2.setTextureSize(128, 64);
        this.setRotation(this.Frontcloth2, -0.3316126f, 0.0f, 0.0f);
        this.bipedHeadwear.cubeList.clear();
        this.bipedHead.cubeList.clear();
        this.bipedHead.addChild(this.Helmet);
        this.bipedBody.cubeList.clear();
        this.bipedRightLeg.cubeList.clear();
        this.bipedLeftLeg.cubeList.clear();
        this.bipedBody.addChild(this.Mbelt);
        this.bipedBody.addChild(this.MbeltL);
        this.bipedBody.addChild(this.MbeltR);
        if (f >= 1.0f) {
            this.bipedBody.addChild(this.Chestplate);
            this.bipedBody.addChild(this.Frontcloth1);
            this.bipedBody.addChild(this.Frontcloth2);
            this.bipedBody.addChild(this.Tabbard);
            this.bipedBody.addChild(this.Backplate);
            this.bipedBody.addChild(this.Cloak1);
            this.bipedBody.addChild(this.Cloak2);
            this.bipedBody.addChild(this.Cloak3);
            this.bipedBody.addChild(this.CloakAtL);
            this.bipedBody.addChild(this.CloakAtR);
        }
        this.bipedRightArm.cubeList.clear();
        this.bipedRightArm.addChild(this.ShoulderR);
        this.bipedRightArm.addChild(this.ShoulderR0);
        this.bipedRightArm.addChild(this.ShoulderR1);
        this.bipedRightArm.addChild(this.ShoulderR2);
        this.bipedRightArm.addChild(this.GauntletR);
        this.bipedRightArm.addChild(this.GauntletstrapR1);
        this.bipedRightArm.addChild(this.GauntletstrapR2);
        this.bipedLeftArm.cubeList.clear();
        this.bipedLeftArm.addChild(this.ShoulderL);
        this.bipedLeftArm.addChild(this.ShoulderL0);
        this.bipedLeftArm.addChild(this.ShoulderL1);
        this.bipedLeftArm.addChild(this.ShoulderL2);
        this.bipedLeftArm.addChild(this.GauntletL);
        this.bipedLeftArm.addChild(this.GauntletstrapL1);
        this.bipedLeftArm.addChild(this.GauntletstrapL2);
        this.bipedRightLeg.addChild(this.SidepanelR0);
        this.bipedRightLeg.addChild(this.SidepanelR1);
        this.bipedRightLeg.addChild(this.SidepanelR2);
        this.bipedRightLeg.addChild(this.SidepanelR3);
        this.bipedLeftLeg.addChild(this.SidepanelL0);
        this.bipedLeftLeg.addChild(this.SidepanelL1);
        this.bipedLeftLeg.addChild(this.SidepanelL2);
        this.bipedLeftLeg.addChild(this.SidepanelL3);
    }
    
    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        final float a = MathHelper.cos(f * 0.6662f) * 1.4f * f1;
        final float b = MathHelper.cos(f * 0.6662f + 3.1415927f) * 1.4f * f1;
        final float c = Math.min(a, b);
        this.Frontcloth1.rotateAngleX = c - 0.1047198f;
        this.Frontcloth2.rotateAngleX = c - 0.3316126f;
        this.Cloak1.rotateAngleX = -c / 2.0f + 0.1396263f;
        this.Cloak2.rotateAngleX = -c / 2.0f + 0.3069452f;
        this.Cloak3.rotateAngleX = -c / 2.0f + 0.4465716f;
        if (this.isChild) {
            final float f6 = 2.0f;
            GL11.glPushMatrix();
            GL11.glScalef(1.5f / f6, 1.5f / f6, 1.5f / f6);
            GL11.glTranslatef(0.0f, 16.0f * f5, 0.0f);
            this.bipedHead.render(f5);
            GL11.glPopMatrix();
            GL11.glPushMatrix();
            GL11.glScalef(1.0f / f6, 1.0f / f6, 1.0f / f6);
            GL11.glTranslatef(0.0f, 24.0f * f5, 0.0f);
            this.bipedBody.render(f5);
            this.bipedRightArm.render(f5);
            this.bipedLeftArm.render(f5);
            this.bipedRightLeg.render(f5);
            this.bipedLeftLeg.render(f5);
            this.bipedHeadwear.render(f5);
            GL11.glPopMatrix();
        }
        else {
            GL11.glPushMatrix();
            GL11.glScalef(1.01f, 1.01f, 1.01f);
            this.bipedHead.render(f5);
            GL11.glPopMatrix();
            this.bipedBody.render(f5);
            this.bipedRightArm.render(f5);
            this.bipedLeftArm.render(f5);
            this.bipedRightLeg.render(f5);
            this.bipedLeftLeg.render(f5);
            this.bipedHeadwear.render(f5);
        }
    }
    
    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
