// 
// Decompiled by Procyon v0.6.0
// 

package thaumcraft.client.renderers.models.gear;

import org.lwjgl.opengl.GL11;
import net.minecraft.util.math.MathHelper;
import net.minecraft.entity.Entity;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelRobe extends ModelCustomArmor
{
    ModelRenderer Hood1;
    ModelRenderer Hood2;
    ModelRenderer Hood3;
    ModelRenderer Hood4;
    ModelRenderer Chestthing;
    ModelRenderer Mbelt;
    ModelRenderer MbeltB;
    ModelRenderer ClothchestL;
    ModelRenderer ClothchestR;
    ModelRenderer Book;
    ModelRenderer Scroll;
    ModelRenderer BeltR;
    ModelRenderer Backplate;
    ModelRenderer MbeltL;
    ModelRenderer MbeltR;
    ModelRenderer BeltL;
    ModelRenderer Chestplate;
    ModelRenderer ShoulderplateR1;
    ModelRenderer ShoulderplateR2;
    ModelRenderer ShoulderplateR3;
    ModelRenderer ShoulderplateTopR;
    ModelRenderer RArm1;
    ModelRenderer RArm2;
    ModelRenderer RArm3;
    ModelRenderer LArm1;
    ModelRenderer LArm2;
    ModelRenderer LArm3;
    ModelRenderer ShoulderplateL1;
    ModelRenderer ShoulderplateL2;
    ModelRenderer ShoulderplateL3;
    ModelRenderer ShoulderplateTopL;
    ModelRenderer ShoulderL;
    ModelRenderer ShoulderR;
    ModelRenderer ClothBackR3;
    ModelRenderer FrontclothR2;
    ModelRenderer FrontclothR1;
    ModelRenderer SideclothR2;
    ModelRenderer SideclothR1;
    ModelRenderer SideclothR3;
    ModelRenderer ClothBackR1;
    ModelRenderer ClothBackR2;
    ModelRenderer SidepanelR1;
    ModelRenderer LegpanelR6;
    ModelRenderer LegpanelR5;
    ModelRenderer LegpanelR4;
    ModelRenderer FrontclothL2;
    ModelRenderer ClothBackL3;
    ModelRenderer ClothBackL1;
    ModelRenderer FrontclothL1;
    ModelRenderer SideclothL2;
    ModelRenderer SideclothL3;
    ModelRenderer Focipouch;
    ModelRenderer SideclothL1;
    ModelRenderer ClothBackL2;
    ModelRenderer LegpanelL4;
    ModelRenderer LegpanelL5;
    ModelRenderer LegpanelL6;
    ModelRenderer SidepanelL1;
    
    public ModelRobe(final float f) {
        super(f, 0, 128, 64);
        this.textureWidth = 128;
        this.textureHeight = 64;
        (this.Hood1 = new ModelRenderer(this, 16, 7)).addBox(-4.5f, -9.0f, -4.6f, 9, 9, 9);
        this.Hood1.setTextureSize(128, 64);
        this.setRotation(this.Hood1, 0.0f, 0.0f, 0.0f);
        (this.Hood2 = new ModelRenderer(this, 52, 13)).addBox(-4.0f, -9.7f, 2.0f, 8, 9, 3);
        this.Hood2.setTextureSize(128, 64);
        this.setRotation(this.Hood2, -0.2268928f, 0.0f, 0.0f);
        (this.Hood3 = new ModelRenderer(this, 52, 14)).addBox(-3.5f, -10.0f, 3.5f, 7, 8, 3);
        this.Hood3.setTextureSize(128, 64);
        this.setRotation(this.Hood3, -0.3490659f, 0.0f, 0.0f);
        (this.Hood4 = new ModelRenderer(this, 53, 15)).addBox(-3.0f, -10.7f, 3.5f, 6, 7, 3);
        this.Hood4.setTextureSize(128, 64);
        this.setRotation(this.Hood4, -0.5759587f, 0.0f, 0.0f);
        (this.Chestthing = new ModelRenderer(this, 56, 50)).addBox(-2.5f, 1.0f, -4.0f, 5, 7, 1);
        this.Chestthing.setTextureSize(128, 64);
        this.setRotation(this.Chestthing, 0.0f, 0.0f, 0.0f);
        (this.Mbelt = new ModelRenderer(this, 16, 55)).addBox(-4.0f, 7.0f, -3.0f, 8, 5, 1);
        this.Mbelt.setTextureSize(128, 64);
        this.setRotation(this.Mbelt, 0.0f, 0.0f, 0.0f);
        (this.MbeltB = new ModelRenderer(this, 16, 55)).addBox(-4.0f, 7.0f, -4.0f, 8, 5, 1);
        this.MbeltB.setTextureSize(128, 64);
        this.setRotation(this.MbeltB, 0.0f, 3.141593f, 0.0f);
        this.ClothchestL = new ModelRenderer(this, 108, 38);
        this.ClothchestL.mirror = true;
        this.ClothchestL.addBox(2.1f, 0.5f, -3.5f, 2, 8, 1);
        this.ClothchestL.setTextureSize(128, 64);
        this.setRotation(this.ClothchestL, 0.0f, 0.0f, 0.0f);
        (this.ClothchestR = new ModelRenderer(this, 108, 38)).addBox(-4.1f, 0.5f, -3.5f, 2, 8, 1);
        this.ClothchestR.setTextureSize(128, 64);
        this.setRotation(this.ClothchestR, 0.0f, 0.0f, 0.0f);
        (this.Book = new ModelRenderer(this, 81, 16)).addBox(1.0f, 0.0f, 4.0f, 5, 7, 2);
        this.Book.setTextureSize(128, 64);
        this.setRotation(this.Book, 0.0f, 0.0f, 0.7679449f);
        (this.Scroll = new ModelRenderer(this, 78, 25)).addBox(-2.0f, 9.5f, 4.0f, 8, 3, 3);
        this.Scroll.setTextureSize(128, 64);
        this.setRotation(this.Scroll, 0.0f, 0.0f, 0.1919862f);
        (this.BeltR = new ModelRenderer(this, 16, 36)).addBox(-5.0f, 4.0f, -3.0f, 1, 3, 6);
        this.BeltR.setTextureSize(128, 64);
        this.setRotation(this.BeltR, 0.0f, 0.0f, 0.0f);
        (this.Backplate = new ModelRenderer(this, 36, 45)).addBox(-4.0f, 1.0f, 1.9f, 8, 11, 2);
        this.Backplate.setTextureSize(128, 64);
        this.setRotation(this.Backplate, 0.0f, 0.0f, 0.0f);
        (this.MbeltL = new ModelRenderer(this, 16, 36)).addBox(4.0f, 8.0f, -3.0f, 1, 3, 6);
        this.MbeltL.setTextureSize(128, 64);
        this.setRotation(this.MbeltL, 0.0f, 0.0f, 0.0f);
        (this.MbeltR = new ModelRenderer(this, 16, 36)).addBox(-5.0f, 8.0f, -3.0f, 1, 3, 6);
        this.MbeltR.setTextureSize(128, 64);
        this.setRotation(this.MbeltR, 0.0f, 0.0f, 0.0f);
        (this.BeltL = new ModelRenderer(this, 16, 36)).addBox(4.0f, 4.0f, -3.0f, 1, 3, 6);
        this.BeltL.setTextureSize(128, 64);
        this.setRotation(this.BeltL, 0.0f, 0.0f, 0.0f);
        (this.Chestplate = new ModelRenderer(this, 16, 25)).addBox(-4.0f, 1.0f, -3.0f, 8, 6, 1);
        this.Chestplate.setTextureSize(128, 64);
        this.setRotation(this.Chestplate, 0.0f, 0.0f, 0.0f);
        (this.ShoulderplateR1 = new ModelRenderer(this, 56, 33)).addBox(-4.5f, -1.5f, -3.5f, 1, 4, 7);
        this.ShoulderplateR1.setTextureSize(128, 64);
        this.setRotation(this.ShoulderplateR1, 0.0f, 0.0f, 0.4363323f);
        (this.ShoulderplateR2 = new ModelRenderer(this, 40, 33)).addBox(-3.5f, 1.5f, -3.5f, 1, 3, 7);
        this.ShoulderplateR2.setTextureSize(128, 64);
        this.setRotation(this.ShoulderplateR2, 0.0f, 0.0f, 0.4363323f);
        (this.ShoulderplateR3 = new ModelRenderer(this, 40, 33)).addBox(-2.5f, 3.5f, -3.5f, 1, 3, 7);
        this.ShoulderplateR3.setTextureSize(128, 64);
        this.setRotation(this.ShoulderplateR3, 0.0f, 0.0f, 0.4363323f);
        (this.ShoulderplateTopR = new ModelRenderer(this, 56, 25)).addBox(-5.5f, -2.5f, -3.5f, 2, 1, 7);
        this.ShoulderplateTopR.setTextureSize(128, 64);
        this.setRotation(this.ShoulderplateTopR, 0.0f, 0.0f, 0.4363323f);
        (this.RArm1 = new ModelRenderer(this, 88, 39)).addBox(-3.5f, 2.5f, -2.5f, 5, 7, 5);
        this.RArm1.setTextureSize(128, 64);
        this.setRotation(this.RArm1, 0.0f, 0.0f, 0.0f);
        (this.RArm2 = new ModelRenderer(this, 76, 32)).addBox(-3.0f, 5.5f, 2.5f, 4, 4, 2);
        this.RArm2.setTextureSize(128, 64);
        this.setRotation(this.RArm2, 0.0f, 0.0f, 0.0f);
        (this.RArm3 = new ModelRenderer(this, 88, 32)).addBox(-2.5f, 3.5f, 2.5f, 3, 2, 1);
        this.RArm3.setTextureSize(128, 64);
        this.setRotation(this.RArm3, 0.0f, 0.0f, 0.0f);
        (this.ShoulderplateL1 = new ModelRenderer(this, 56, 33)).addBox(3.5f, -1.5f, -3.5f, 1, 4, 7);
        this.ShoulderplateL1.setTextureSize(128, 64);
        this.setRotation(this.ShoulderplateL1, 0.0f, 0.0f, -0.4363323f);
        (this.ShoulderplateL2 = new ModelRenderer(this, 40, 33)).addBox(2.5f, 1.5f, -3.5f, 1, 3, 7);
        this.ShoulderplateL2.setTextureSize(128, 64);
        this.setRotation(this.ShoulderplateL2, 0.0f, 0.0f, -0.4363323f);
        (this.ShoulderplateL3 = new ModelRenderer(this, 40, 33)).addBox(1.5f, 3.5f, -3.5f, 1, 3, 7);
        this.ShoulderplateL3.setTextureSize(128, 64);
        this.setRotation(this.ShoulderplateL3, 0.0f, 0.0f, -0.4363323f);
        (this.ShoulderplateTopL = new ModelRenderer(this, 56, 25)).addBox(3.5f, -2.5f, -3.5f, 2, 1, 7);
        this.ShoulderplateTopL.setTextureSize(128, 64);
        this.setRotation(this.ShoulderplateTopL, 0.0f, 0.0f, -0.4363323f);
        this.ShoulderR = new ModelRenderer(this, 16, 45);
        this.ShoulderR.mirror = true;
        this.ShoulderR.addBox(-3.5f, -2.5f, -2.5f, 5, 5, 5);
        this.ShoulderR.setTextureSize(128, 64);
        this.setRotation(this.ShoulderR, 0.0f, 0.0f, 0.0f);
        this.LArm1 = new ModelRenderer(this, 88, 39);
        this.LArm1.mirror = true;
        this.LArm1.addBox(-1.5f, 2.5f, -2.5f, 5, 7, 5);
        this.LArm1.setTextureSize(128, 64);
        this.setRotation(this.LArm1, 0.0f, 0.0f, 0.0f);
        (this.LArm2 = new ModelRenderer(this, 76, 32)).addBox(-1.0f, 5.5f, 2.5f, 4, 4, 2);
        this.LArm2.setTextureSize(128, 64);
        this.setRotation(this.LArm2, 0.0f, 0.0f, 0.0f);
        (this.LArm3 = new ModelRenderer(this, 88, 32)).addBox(-0.5f, 3.5f, 2.5f, 3, 2, 1);
        this.LArm3.setTextureSize(128, 64);
        this.setRotation(this.LArm3, 0.0f, 0.0f, 0.0f);
        (this.ShoulderL = new ModelRenderer(this, 16, 45)).addBox(-1.5f, -2.5f, -2.5f, 5, 5, 5);
        this.ShoulderL.setTextureSize(128, 64);
        this.ShoulderL.mirror = true;
        this.setRotation(this.ShoulderL, 0.0f, 0.0f, 0.0f);
        (this.FrontclothR1 = new ModelRenderer(this, 108, 38)).addBox(0.0f, 0.0f, 0.0f, 3, 8, 1);
        this.FrontclothR1.setRotationPoint(-3.0f, 11.0f, -2.9f);
        this.FrontclothR1.setTextureSize(128, 64);
        this.setRotation(this.FrontclothR1, -0.1047198f, 0.0f, 0.0f);
        (this.FrontclothR2 = new ModelRenderer(this, 108, 47)).addBox(0.0f, 7.5f, 1.7f, 3, 3, 1);
        this.FrontclothR2.setRotationPoint(-3.0f, 11.0f, -2.9f);
        this.FrontclothR2.setTextureSize(128, 64);
        this.setRotation(this.FrontclothR2, -0.3316126f, 0.0f, 0.0f);
        this.FrontclothL1 = new ModelRenderer(this, 108, 38);
        this.FrontclothL1.mirror = true;
        this.FrontclothL1.addBox(0.0f, 0.0f, 0.0f, 3, 8, 1);
        this.FrontclothL1.setRotationPoint(0.0f, 11.0f, -2.9f);
        this.FrontclothL1.setTextureSize(128, 64);
        this.setRotation(this.FrontclothL1, -0.1047198f, 0.0f, 0.0f);
        this.FrontclothL2 = new ModelRenderer(this, 108, 47);
        this.FrontclothL2.mirror = true;
        this.FrontclothL2.addBox(0.0f, 7.5f, 1.7f, 3, 3, 1);
        this.FrontclothL2.setRotationPoint(0.0f, 11.0f, -2.9f);
        this.FrontclothL2.setTextureSize(128, 64);
        this.setRotation(this.FrontclothL2, -0.3316126f, 0.0f, 0.0f);
        this.ClothBackR1 = new ModelRenderer(this, 118, 16);
        this.ClothBackR1.mirror = true;
        this.ClothBackR1.addBox(0.0f, 0.0f, 0.0f, 4, 8, 1);
        this.ClothBackR1.setRotationPoint(-4.0f, 11.5f, 2.9f);
        this.ClothBackR1.setTextureSize(128, 64);
        this.setRotation(this.ClothBackR1, 0.1047198f, 0.0f, 0.0f);
        (this.ClothBackR2 = new ModelRenderer(this, 123, 9)).addBox(0.0f, 7.8f, -0.9f, 1, 2, 1);
        this.ClothBackR2.setRotationPoint(-4.0f, 11.5f, 2.9f);
        this.ClothBackR2.setTextureSize(128, 64);
        this.setRotation(this.ClothBackR2, 0.2268928f, 0.0f, 0.0f);
        this.ClothBackR3 = new ModelRenderer(this, 120, 12);
        this.ClothBackR3.mirror = true;
        this.ClothBackR3.addBox(1.0f, 7.8f, -0.9f, 3, 3, 1);
        this.ClothBackR3.setRotationPoint(-4.0f, 11.5f, 2.9f);
        this.ClothBackR3.setTextureSize(128, 64);
        this.setRotation(this.ClothBackR3, 0.2268928f, 0.0f, 0.0f);
        (this.ClothBackL1 = new ModelRenderer(this, 118, 16)).addBox(0.0f, 0.0f, 0.0f, 4, 8, 1);
        this.ClothBackL1.setRotationPoint(0.0f, 11.5f, 2.9f);
        this.ClothBackL1.setTextureSize(128, 64);
        this.setRotation(this.ClothBackL1, 0.1047198f, 0.0f, 0.0f);
        this.ClothBackL2 = new ModelRenderer(this, 123, 9);
        this.ClothBackL2.mirror = true;
        this.ClothBackL2.addBox(3.0f, 7.8f, -0.9f, 1, 2, 1);
        this.ClothBackL2.setRotationPoint(0.0f, 11.5f, 2.9f);
        this.ClothBackL2.setTextureSize(128, 64);
        this.setRotation(this.ClothBackL2, 0.2268928f, 0.0f, 0.0f);
        (this.ClothBackL3 = new ModelRenderer(this, 120, 12)).addBox(0.0f, 7.8f, -0.9f, 3, 3, 1);
        this.ClothBackL3.setRotationPoint(0.0f, 11.5f, 2.9f);
        this.ClothBackL3.setTextureSize(128, 64);
        this.setRotation(this.ClothBackL3, 0.2268928f, 0.0f, 0.0f);
        (this.SideclothL2 = new ModelRenderer(this, 116, 34)).addBox(0.5f, 5.5f, -2.5f, 1, 3, 5);
        this.SideclothL2.setTextureSize(128, 64);
        this.setRotation(this.SideclothL2, 0.0f, 0.0f, -0.296706f);
        (this.SideclothR1 = new ModelRenderer(this, 116, 42)).addBox(-2.5f, 0.5f, -2.5f, 1, 5, 5);
        this.SideclothR1.setTextureSize(128, 64);
        this.setRotation(this.SideclothR1, 0.0f, 0.0f, 0.122173f);
        (this.SideclothR2 = new ModelRenderer(this, 116, 34)).addBox(-1.5f, 5.5f, -2.5f, 1, 3, 5);
        this.SideclothR2.setTextureSize(128, 64);
        this.setRotation(this.SideclothR2, 0.0f, 0.0f, 0.296706f);
        (this.SideclothR3 = new ModelRenderer(this, 116, 1)).addBox(0.4f, 8.4f, -2.5f, 1, 3, 5);
        this.SideclothR3.setTextureSize(128, 64);
        this.setRotation(this.SideclothR3, 0.0f, 0.0f, 0.5235988f);
        (this.SidepanelR1 = new ModelRenderer(this, 116, 25)).addBox(-2.5f, 0.5f, -2.5f, 1, 4, 5);
        this.SidepanelR1.setTextureSize(128, 64);
        this.SidepanelR1.mirror = true;
        this.setRotation(this.SidepanelR1, 0.0f, 0.0f, 0.4363323f);
        (this.LegpanelR6 = new ModelRenderer(this, 82, 38)).addBox(-3.0f, 4.5f, -1.5f, 2, 3, 1);
        this.LegpanelR6.setTextureSize(128, 64);
        this.setRotation(this.LegpanelR6, -0.4363323f, 0.0f, 0.0f);
        (this.LegpanelR5 = new ModelRenderer(this, 76, 42)).addBox(-3.0f, 2.5f, -2.5f, 2, 3, 1);
        this.LegpanelR5.setTextureSize(128, 64);
        this.setRotation(this.LegpanelR5, -0.4363323f, 0.0f, 0.0f);
        (this.LegpanelR4 = new ModelRenderer(this, 76, 38)).addBox(-3.0f, 0.5f, -3.5f, 2, 3, 1);
        this.LegpanelR4.setTextureSize(128, 64);
        this.setRotation(this.LegpanelR4, -0.4363323f, 0.0f, 0.0f);
        (this.SideclothL3 = new ModelRenderer(this, 116, 1)).addBox(-1.4f, 8.4f, -2.5f, 1, 3, 5);
        this.SideclothL3.setTextureSize(128, 64);
        this.setRotation(this.SideclothL3, 0.0f, 0.0f, -0.5235988f);
        (this.Focipouch = new ModelRenderer(this, 100, 20)).addBox(3.5f, 0.5f, -2.5f, 3, 6, 5);
        this.Focipouch.setTextureSize(128, 64);
        this.setRotation(this.Focipouch, 0.0f, 0.0f, -0.122173f);
        (this.SideclothL1 = new ModelRenderer(this, 116, 42)).addBox(1.5f, 0.5f, -2.5f, 1, 5, 5);
        this.SideclothL1.setTextureSize(128, 64);
        this.setRotation(this.SideclothL1, 0.0f, 0.0f, -0.122173f);
        this.LegpanelL4 = new ModelRenderer(this, 76, 38);
        this.LegpanelL4.mirror = true;
        this.LegpanelL4.addBox(1.0f, 0.5f, -3.5f, 2, 3, 1);
        this.LegpanelL4.setTextureSize(128, 64);
        this.setRotation(this.LegpanelL4, -0.4363323f, 0.0f, 0.0f);
        this.LegpanelL5 = new ModelRenderer(this, 76, 42);
        this.LegpanelL5.mirror = true;
        this.LegpanelL5.addBox(1.0f, 2.5f, -2.5f, 2, 3, 1);
        this.LegpanelL5.setTextureSize(128, 64);
        this.setRotation(this.LegpanelL5, -0.4363323f, 0.0f, 0.0f);
        this.LegpanelL6 = new ModelRenderer(this, 82, 38);
        this.LegpanelL6.mirror = true;
        this.LegpanelL6.addBox(1.0f, 4.5f, -1.5f, 2, 3, 1);
        this.LegpanelL6.setTextureSize(128, 64);
        this.setRotation(this.LegpanelL6, -0.4363323f, 0.0f, 0.0f);
        (this.SidepanelL1 = new ModelRenderer(this, 116, 25)).addBox(1.5f, 0.5f, -2.5f, 1, 4, 5);
        this.SidepanelL1.setTextureSize(128, 64);
        this.setRotation(this.SidepanelL1, 0.0f, 0.0f, -0.4363323f);
        this.bipedHeadwear.cubeList.clear();
        this.bipedHead.cubeList.clear();
        this.bipedHead.addChild(this.Hood1);
        this.bipedHead.addChild(this.Hood2);
        this.bipedHead.addChild(this.Hood3);
        this.bipedHead.addChild(this.Hood4);
        this.bipedBody.cubeList.clear();
        this.bipedRightLeg.cubeList.clear();
        this.bipedLeftLeg.cubeList.clear();
        this.bipedBody.addChild(this.Mbelt);
        this.bipedBody.addChild(this.MbeltB);
        this.bipedBody.addChild(this.MbeltL);
        this.bipedBody.addChild(this.MbeltR);
        if (f < 1.0f) {
            this.bipedLeftLeg.addChild(this.Focipouch);
            this.bipedBody.addChild(this.FrontclothR1);
            this.bipedBody.addChild(this.FrontclothR2);
            this.bipedBody.addChild(this.FrontclothL1);
            this.bipedBody.addChild(this.FrontclothL2);
            this.bipedBody.addChild(this.ClothBackR1);
            this.bipedBody.addChild(this.ClothBackR2);
            this.bipedBody.addChild(this.ClothBackR3);
            this.bipedBody.addChild(this.ClothBackL1);
            this.bipedBody.addChild(this.ClothBackL2);
            this.bipedBody.addChild(this.ClothBackL3);
        }
        else {
            this.bipedBody.addChild(this.Chestplate);
            this.bipedBody.addChild(this.Chestthing);
            this.bipedBody.addChild(this.Scroll);
            this.bipedBody.addChild(this.Backplate);
            this.bipedBody.addChild(this.Book);
            this.bipedBody.addChild(this.ClothchestL);
            this.bipedBody.addChild(this.ClothchestR);
        }
        this.bipedRightArm.cubeList.clear();
        this.bipedRightArm.addChild(this.ShoulderR);
        this.bipedRightArm.addChild(this.RArm1);
        this.bipedRightArm.addChild(this.RArm2);
        this.bipedRightArm.addChild(this.RArm3);
        this.bipedRightArm.addChild(this.ShoulderplateTopR);
        this.bipedRightArm.addChild(this.ShoulderplateR1);
        this.bipedRightArm.addChild(this.ShoulderplateR2);
        this.bipedRightArm.addChild(this.ShoulderplateR3);
        this.bipedLeftArm.cubeList.clear();
        this.bipedLeftArm.addChild(this.ShoulderL);
        this.bipedLeftArm.addChild(this.LArm1);
        this.bipedLeftArm.addChild(this.LArm2);
        this.bipedLeftArm.addChild(this.LArm3);
        this.bipedLeftArm.addChild(this.ShoulderplateTopL);
        this.bipedLeftArm.addChild(this.ShoulderplateL1);
        this.bipedLeftArm.addChild(this.ShoulderplateL2);
        this.bipedLeftArm.addChild(this.ShoulderplateL3);
        this.bipedRightLeg.addChild(this.LegpanelR4);
        this.bipedRightLeg.addChild(this.LegpanelR5);
        this.bipedRightLeg.addChild(this.LegpanelR6);
        this.bipedRightLeg.addChild(this.SidepanelR1);
        this.bipedRightLeg.addChild(this.SideclothR1);
        this.bipedRightLeg.addChild(this.SideclothR2);
        this.bipedRightLeg.addChild(this.SideclothR3);
        this.bipedLeftLeg.addChild(this.LegpanelL4);
        this.bipedLeftLeg.addChild(this.LegpanelL5);
        this.bipedLeftLeg.addChild(this.LegpanelL6);
        this.bipedLeftLeg.addChild(this.SidepanelL1);
        this.bipedLeftLeg.addChild(this.SideclothL1);
        this.bipedLeftLeg.addChild(this.SideclothL2);
        this.bipedLeftLeg.addChild(this.SideclothL3);
    }
    
    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        final float a = MathHelper.cos(f * 0.6662f) * 1.4f * f1;
        final float b = MathHelper.cos(f * 0.6662f + 3.1415927f) * 1.4f * f1;
        final float c = Math.min(a, b);
        final ModelRenderer frontclothR1 = this.FrontclothR1;
        final ModelRenderer frontclothL1 = this.FrontclothL1;
        final float n = c - 0.1047198f;
        frontclothL1.rotateAngleX = n;
        frontclothR1.rotateAngleX = n;
        final ModelRenderer frontclothR2 = this.FrontclothR2;
        final ModelRenderer frontclothL2 = this.FrontclothL2;
        final float n2 = c - 0.3316126f;
        frontclothL2.rotateAngleX = n2;
        frontclothR2.rotateAngleX = n2;
        final ModelRenderer clothBackR1 = this.ClothBackR1;
        final ModelRenderer clothBackL1 = this.ClothBackL1;
        final float n3 = -c + 0.1047198f;
        clothBackL1.rotateAngleX = n3;
        clothBackR1.rotateAngleX = n3;
        final ModelRenderer clothBackR2 = this.ClothBackR2;
        final ModelRenderer clothBackL2 = this.ClothBackL2;
        final ModelRenderer clothBackR3 = this.ClothBackR3;
        final ModelRenderer clothBackL3 = this.ClothBackL3;
        final float n4 = -c + 0.2268928f;
        clothBackL3.rotateAngleX = n4;
        clothBackR3.rotateAngleX = n4;
        clothBackL2.rotateAngleX = n4;
        clothBackR2.rotateAngleX = n4;
        if (this.isChild) {
            final float f6 = 2.0f;
            GL11.glPushMatrix();
            GL11.glScalef(1.5f / f6, 1.5f / f6, 1.5f / f6);
            GL11.glTranslatef(0.0f, 16.0f * f5, 0.0f);
            this.bipedHead.render(f5);
            GL11.glPopMatrix();
            GL11.glPushMatrix();
            GL11.glScalef(1.0f / f6, 1.0f / f6, 1.0f / f6);
            GL11.glTranslatef(0.0f, 24.0f * f5, 0.0f);
            this.bipedBody.render(f5);
            this.bipedRightArm.render(f5);
            this.bipedLeftArm.render(f5);
            this.bipedRightLeg.render(f5);
            this.bipedLeftLeg.render(f5);
            this.bipedHeadwear.render(f5);
            GL11.glPopMatrix();
        }
        else {
            GL11.glPushMatrix();
            GL11.glScalef(1.01f, 1.01f, 1.01f);
            this.bipedHead.render(f5);
            GL11.glPopMatrix();
            this.bipedBody.render(f5);
            this.bipedRightArm.render(f5);
            this.bipedLeftArm.render(f5);
            this.bipedRightLeg.render(f5);
            this.bipedLeftLeg.render(f5);
            this.bipedHeadwear.render(f5);
        }
    }
    
    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
